name: CD

on: #[push]
    schedule:
        - cron: '0 0 * * 0'  # weekly

jobs:
    build:

        name: Download the necessary files and build
        runs-on: ubuntu-latest

        steps:
            - name: checkout the repo
              uses: actions/checkout@v1
            - name: install setuptools
              run: sudo apt-get install -y python3-setuptools
            - name: install python dependencies
              run:  pip3 install --upgrade telethon google-api-python-client google-auth-httplib2 google-auth-oauthlib
            - name: save secrets
              env:
                  FILE_IDS: ${{secrets.DRIVE_FILE_IDS}}
                  TOKEN_DATA: ${{secrets.DRIVE_TOKEN_DATA}}
                  TG_SESSION: ${{secrets.TG_SESSION}}
              run: |
                echo $FILE_IDS > drive_file_ids.json
                echo $TOKEN_DATA > drive_token.json
                echo $TG_SESSION > .session
            - name: get needed files from drive, update data and post
              run:  python3 -m comms build
