name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
     - name: checkout the repo
       uses: actions/checkout@v1
     - name: List the directory and other info
       run: |
            ls
            pip3 --version
            python3 --version
