name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: create a file and commit it
      run: |
        touch t.test
        echo "foo bar" > t.test
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git add .
        git commit -m "Update trial file"
        git push github HEAD:${GITHUB_REF}
